Data Cleaning

In [54]:
import pandas as pd

In [55]:
data_pgk = pd.read_csv('penyakit_ginjal_kronik.csv')
data_pgk

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
0,0,48.0,80.0,1.020,1.0,0.0,NaN,Tidak Normal,121.0,36.0,...,44,7800,5.2,yes,yes,Tidak,baik,Tidak,Tidak,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,Tidak Normal,NaN,18.0,...,38,6000,NaN,Tidak,Tidak,Tidak,baik,Tidak,Tidak,ckd
2,2,62.0,80.0,1.010,2.0,3.0,Tidak Normal,Tidak Normal,423.0,53.0,...,31,7500,NaN,Tidak,yes,Tidak,buruk,Tidak,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,Tidak Normal,Normal,117.0,56.0,...,32,6700,3.9,yes,Tidak,Tidak,buruk,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,Tidak Normal,Tidak Normal,106.0,26.0,...,35,7300,4.6,Tidak,Tidak,Tidak,baik,Tidak,Tidak,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,140.0,49.0,...,47,6700,4.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
396,396,42.0,70.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,75.0,31.0,...,54,7800,6.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
397,397,12.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,100.0,26.0,...,49,6600,5.4,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
398,398,17.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,114.0,50.0,...,51,7200,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
399,399,58.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,131.0,18.0,...,53,6800,6.1,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd

In [56]:
#nomor 1: cari values bernilai NaN
data_pgk.isnull().sum()

id                   0
umur                 9
tekanandarah        12
gravitas            47
albumin             46
sugar               49
seldarahmerah      152
pussel              65
gds                 44
ureum               19
kreatinin           17
natrium             87
kalium              88
hemoglobin          52
MCV                 70
seldarahputih      105
seldarahmerah.1    130
hipertensi           2
diabetes             2
cad                  2
nafsumakan           1
edema                1
anemia               1
klasifikasi          0
dtype: int64

In [57]:
#nomor 2: hapus values NaN pada data
data_pgk_clean = data_pgk.dropna(axis=0)
data_pgk_clean

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
3,3,48.0,70.0,1.005,4.0,0.0,Tidak Normal,Normal,117.0,56.0,...,32,6700,3.9,yes,Tidak,Tidak,buruk,yes,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,Normal,Normal,70.0,107.0,...,29,12100,3.7,yes,yes,Tidak,buruk,Tidak,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,Normal,Normal,380.0,60.0,...,32,4500,3.8,yes,yes,Tidak,buruk,yes,Tidak,ckd
14,14,68.0,80.0,1.010,3.0,2.0,Tidak Normal,Normal,157.0,90.0,...,16,11000,2.6,yes,yes,yes,buruk,yes,Tidak,ckd
20,20,61.0,80.0,1.015,2.0,0.0,Normal,Normal,173.0,148.0,...,24,9200,3.2,yes,yes,yes,buruk,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,140.0,49.0,...,47,6700,4.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
396,396,42.0,70.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,75.0,31.0,...,54,7800,6.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
397,397,12.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,100.0,26.0,...,49,6600,5.4,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
398,398,17.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,114.0,50.0,...,51,7200,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
399,399,58.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,131.0,18.0,...,53,6800,6.1,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd

In [58]:
#nomor 3: ganti value 'yes' dengan 'Iya' pada kolom 'hipertensi' dan 'diabetes'

data_pgk_clean[['hipertensi', 'diabetes']]

    hipertensi diabetes
3          yes    Tidak
9          yes      yes
11         yes      yes
14         yes      yes
20         yes      yes
..         ...      ...
395      Tidak    Tidak
396      Tidak    Tidak
397      Tidak    Tidak
398      Tidak    Tidak
399      Tidak    Tidak

[159 rows x 2 columns]

In [59]:
data_pgk_clean[['hipertensi', 'diabetes']] = data_pgk_clean[['hipertensi', 'diabetes']].replace('yes', 'Iya')
data_pgk_clean[['hipertensi', 'diabetes']]

C:\Users\Emik\AppData\Local\Temp\ipykernel_2140\3362476052.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_pgk_clean[['hipertensi', 'diabetes']] = data_pgk_clean[['hipertensi', 'diabetes']].replace('yes', 'Iya')

    hipertensi diabetes
3          Iya    Tidak
9          Iya      Iya
11         Iya      Iya
14         Iya      Iya
20         Iya      Iya
..         ...      ...
395      Tidak    Tidak
396      Tidak    Tidak
397      Tidak    Tidak
398      Tidak    Tidak
399      Tidak    Tidak

[159 rows x 2 columns]

In [60]:
data_pgk_clean

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
3,3,48.0,70.0,1.005,4.0,0.0,Tidak Normal,Normal,117.0,56.0,...,32,6700,3.9,Iya,Tidak,Tidak,buruk,yes,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,Normal,Normal,70.0,107.0,...,29,12100,3.7,Iya,Iya,Tidak,buruk,Tidak,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,Normal,Normal,380.0,60.0,...,32,4500,3.8,Iya,Iya,Tidak,buruk,yes,Tidak,ckd
14,14,68.0,80.0,1.010,3.0,2.0,Tidak Normal,Normal,157.0,90.0,...,16,11000,2.6,Iya,Iya,yes,buruk,yes,Tidak,ckd
20,20,61.0,80.0,1.015,2.0,0.0,Normal,Normal,173.0,148.0,...,24,9200,3.2,Iya,Iya,yes,buruk,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,140.0,49.0,...,47,6700,4.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
396,396,42.0,70.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,75.0,31.0,...,54,7800,6.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
397,397,12.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,100.0,26.0,...,49,6600,5.4,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
398,398,17.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,114.0,50.0,...,51,7200,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
399,399,58.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,131.0,18.0,...,53,6800,6.1,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd

In [61]:
#nomor 4: banyak data sebelum dan setelah penghapusan

print(f'Data sebelum cleaning: {data_pgk.shape[0]} baris, {data_pgk.shape[1]} kolom')
print(f'Data setelah cleaning: {data_pgk_clean.shape[0]} baris, {data_pgk_clean.shape[1]} kolom')

Data sebelum cleaning: 400 baris, 24 kolom
Data setelah cleaning: 159 baris, 24 kolom